sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
install:
    - npm install
script:
    - npm run lint
    - npm run sasslint
    - npm run unit
    - vue-cli-service build && node build-script.js
